apiVersion: v1
kind: Pod

metadata:
  name: myapp-pod
  namespace: dev
  # The pod is defined in a specific namespace
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
  # The pod definition does not specify replicas, as it is a single pod
  toleration:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"
  # The pod will tolerate nodes with the taint app=blue:NoSchedule
