apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  #not to use in production
  hostPath:
    path: /mnt/data
    fstype: ext4
  persistentVolumeReclaimPolicy: Retain #default is Retain
