apiVersion: v1
kind: Config
current-context: my-kube-admin@my-kube-playground
clusters:
  - name: my-kube-playground
    clusters:
      certificate-authority: ca.crt # Path to CA cert
      # Alternatively, you can use certificate-authority-data for inline CA cert
      certificate-authority-data: <certificate-authority-data> # Base64 encoded CA cert
      server: https://my-kube-playground:1663
  - name: development
    clusters:
      certificate-authority: ca.crt
      server: https://development:1663

contexts:
  - name: my-kube-admin@my-kube-playground
    context:
      cluster: my-kube-playground
      user: my-kube-admin
      namespace: dev

  - name: admin@development
    context:
      cluster: development
      user: admin

users:
  - name: my-kube-admin
    user:
      client-certificate: admin.crt
      client-key: admin.key
  - name: admin
    user:
      client-certificate: admin.crt
      client-key: admin.key
