apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraints
  namespace: default

spec:
  limits:
    - default:
        cpu: 500m
      # This is the default CPU limit for containers in this namespace
      defaultRequest:
        cpu: 500m
      # This is the default CPU request for containers in this namespace
      max:
        cpu: "1"
      # This is the maximum CPU limit for containers in this namespace
      min:
        cpu: 100m
      # This is the minimum CPU request for containers in this namespace
      type: Container
