apiVersion: v1
kind: Service
metadata:
  name: service-stable
spec:
  selector:
    app: app
    version: stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-canary
spec:
  selector:
    app: app
    version: canary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
