apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
# This configuration file is used to set up the Kubernetes scheduler.
profiles:
  - schdulerName: my-scheduler-2
    plugins:
      score:
        disabled:
          - name: TaintToleration
        enabled:
          - name: mycustom-pluginA
          - name: mycustom-pluginB
