apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
# This configuration file is used to set up the Kubernetes scheduler.
profiles:
  - schedulerName: my-scheduler
leaderElection:
  leaderElect: true
  resourceNamespace: kube-system
  resourceName: lock-object-my-scheduler
