apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
  namespace: dev
subjects:
  - kind: User
    name: dev-user
    apiGroups: rbac.authorization.k8s.io
# This RoleBinding grants the developer role to the user dev-user in the dev namespace.
RoleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io
